// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1QVIufQ7huh1tpVEdl6KnixFBysYJnPQ',
    appId: '1:936807897728:web:2c6214a29c31a3b8ada465',
    messagingSenderId: '936807897728',
    projectId: 'e-commerce-app-8d4f9',
    authDomain: 'e-commerce-app-8d4f9.firebaseapp.com',
    storageBucket: 'e-commerce-app-8d4f9.firebasestorage.app',
    measurementId: 'G-19HJM0GL87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDigWwfr8qskSnB1W3iJ_pXseHcGlGcao',
    appId: '1:936807897728:android:41a11696fd96ec3fada465',
    messagingSenderId: '936807897728',
    projectId: 'e-commerce-app-8d4f9',
    storageBucket: 'e-commerce-app-8d4f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3sO0aX9puffoX_EMN0Zp5indB219y9o',
    appId: '1:936807897728:ios:4cd29e07aff8d7f5ada465',
    messagingSenderId: '936807897728',
    projectId: 'e-commerce-app-8d4f9',
    storageBucket: 'e-commerce-app-8d4f9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ3sO0aX9puffoX_EMN0Zp5indB219y9o',
    appId: '1:936807897728:ios:4cd29e07aff8d7f5ada465',
    messagingSenderId: '936807897728',
    projectId: 'e-commerce-app-8d4f9',
    storageBucket: 'e-commerce-app-8d4f9.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1QVIufQ7huh1tpVEdl6KnixFBysYJnPQ',
    appId: '1:936807897728:web:316ceaa977d30774ada465',
    messagingSenderId: '936807897728',
    projectId: 'e-commerce-app-8d4f9',
    authDomain: 'e-commerce-app-8d4f9.firebaseapp.com',
    storageBucket: 'e-commerce-app-8d4f9.firebasestorage.app',
    measurementId: 'G-2CQ9VVFFZP',
  );
}
